#!/usr/bin/env node
// Regenerates packages/shared/abi/CachetRegistry.ts from the Foundry build
// artifact. Run this after any change to the contract, via:
//   pnpm --filter @cachet/shared generate:abi
// Requires `forge build` to have already produced packages/contracts/out/.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const ARTIFACT_PATH = path.join(
  __dirname,
  "../../contracts/out/CachetRegistry.sol/CachetRegistry.json",
);
const OUTPUT_PATH = path.join(__dirname, "../abi/CachetRegistry.ts");

const artifact = JSON.parse(readFileSync(ARTIFACT_PATH, "utf8"));

const banner = `// AUTO-GENERATED by scripts/generate-abi.mjs from the Foundry build artifact.
// Do not hand-edit — run \`pnpm --filter @cachet/shared generate:abi\` instead
// (requires \`forge build\` to have run first in packages/contracts).
`;

const output = `${banner}
export const CachetRegistryAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

writeFileSync(OUTPUT_PATH, output);
console.log(`Wrote ${artifact.abi.length} ABI entries to ${path.relative(process.cwd(), OUTPUT_PATH)}`);
